/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.Vista;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


/**
 *
 * 
 */
public class MatrimonioVista extends javax.swing.JPanel {
    
    private SimpleDateFormat formato;
    private DefaultTableModel defaultTableModel;

    private ResourceBundle recurso;

    /**
     * Creates new form Persona
     */
    public MatrimonioVista() {
        initComponents();
        this.recurso = recurso;
        formato = new SimpleDateFormat("dd/mm/yyyy");
        defaultTableModel = (DefaultTableModel) tblMatrimonio.getModel();
        
        this.cargarDatosTabla();
        this.tblMatrimonio.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                vizualizarDatos(tblMatrimonio.getSelectedRow());
            }
        });
    }
    
   
    
    public void cargarDatosTabla() {
        defaultTableModel.setRowCount(0);
        for (Matrimonio m: registroControlador.getMatrimonioControlador().getListMatrimonio()) {
            String fecha = formato.format(m.getFecha());
            String datos[] = {String.valueOf(m.getId()), m.getLugar(), fecha , m.getEsposo().getApellido() + " " + m.getEsposa().getApellido(), m.getAutoridad().getApellido()};
            defaultTableModel.addRow(datos);
        }
    }
    
    public void vizualizarDatos(int posicion) {
        if(posicion >= 0) {
            Matrimonio m = this.registroControlador.getMatrimonioControlador().getListMatrimonio().get(posicion);
            txtId.setText(String.valueOf(m.getId()));
            txtLugar.setText(m.getLugar());
            txtAutoridad.setText(m.getAutoridad().getCedula());
            lblAutoridad.setText(m.getAutoridad().getNombre() + " " + m.getAutoridad().getApellido());
            txtEsposa.setText(m.getEsposa().getCedula());
            lblEsposa.setText(m.getEsposa().getNombre() + " " + m.getEsposa().getApellido());
            txtEsposo.setText(m.getEsposo().getCedula());
            lblEsposo.setText(m.getEsposo().getNombre() + " " + m.getEsposo().getApellido());
            String fecha = formato.format(m.getFecha());
            txtFecha.setText(fecha);
            txtTestigo.setText("");
            defaultListModel.setSize(0);
            for (Persona p : m.getTestigos()) {
                defaultListModel.addElement(p.getCedula());
            }
        }else{
            txtId.setText("");
            txtLugar.setText("");
            txtAutoridad.setText("");
            txtEsposa.setText("");
            txtEsposo.setText("");
            txtFecha.setText("");
            txtTestigo.setText("");
            defaultListModel.setSize(0);
            lblAutoridad.setText("");
            lblEsposa.setText("");
            lblEsposo.setText("");
            lblTestigo.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLugar = new javax.swing.JLabel();
        lblAutoridadPresentacion = new javax.swing.JLabel();
        lblEsposaPresentacion = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTestigosPresentacion = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        txtAutoridad = new javax.swing.JTextField();
        txtEsposa = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatrimonio = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtTestigo = new javax.swing.JTextField();
        lblAutoridad = new javax.swing.JLabel();
        lblEsposa = new javax.swing.JLabel();
        lblEsposo = new javax.swing.JLabel();
        lblTestigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtConyuge2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTestigo2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        lblLugar.setText("Lugar");

        lblAutoridadPresentacion.setText("Autoridad");

        lblEsposaPresentacion.setText("Conyuge 1");

        lblFecha.setText("Fecha:");

        lblTestigosPresentacion.setText("Testigos 1: ");

        txtAutoridad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAutoridadFocusLost(evt);
            }
        });
        txtAutoridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutoridadActionPerformed(evt);
            }
        });

        txtEsposa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEsposaFocusLost(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setFocusable(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Elminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setFocusable(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setFocusable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblMatrimonio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Lugar", "Fecha", "Pareja", "Juez"
            }
        ));
        jScrollPane1.setViewportView(tblMatrimonio);

        lblId.setText("Id");

        txtId.setEditable(false);

        txtTestigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTestigoFocusLost(evt);
            }
        });
        txtTestigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTestigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Conyuge 2");

        jLabel2.setText("Testigo 2: ");

        txtTestigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTestigo2ActionPerformed(evt);
            }
        });

        jButton1.setText("Actualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAutoridadPresentacion)
                                    .addComponent(lblEsposaPresentacion)
                                    .addComponent(lblTestigosPresentacion))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                                        .addComponent(lblTestigo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtTestigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEsposa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTestigo2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                                    .addComponent(txtConyuge2)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(txtAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEsposo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEsposa, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFecha)
                                            .addComponent(lblLugar))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblId))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(lblFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLugar)
                            .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutoridadPresentacion)
                            .addComponent(txtAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEsposa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEsposo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEsposa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEsposaPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtConyuge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTestigosPresentacion)
                                    .addComponent(txtTestigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTestigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(33, 33, 33)
                .addComponent(lblTestigo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            Date fecha = formato.parse(txtFecha.getText());
            Persona autoridad = this.registroControlador.buscarPersona(txtAutoridad.getText());
            Persona esposo = this.registroControlador.buscarPersona(txtEsposo.getText());
            Persona esposa = this.registroControlador.buscarPersona(txtEsposa.getText());
            List<Persona> testigos = new ArrayList<>();
            for (int i = 0; i < defaultListModel.size(); i++) {
                Persona p = this.registroControlador.buscarPersona(defaultListModel.get(i).toString());
                testigos.add(p);
            }
            String mensaje = "";
            if(txtId.getText().equals("")) {
                mensaje = this.registroControlador.crearMatrimonio(fecha, txtLugar.getText(), esposo, esposa, testigos, autoridad);
            }else {
                mensaje = this.registroControlador.actualizarMatrimonio(Integer.parseInt(txtId.getText()), fecha, txtLugar.getText(), esposo, esposa, testigos, autoridad);
            }
            JOptionPane.showMessageDialog(this, mensaje);
        }catch(ParseException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }finally {
            this.cargarDatosTabla();
            this.vizualizarDatos(-1);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String mensaje = this.registroControlador.eliminarMatrimonio(Integer.parseInt(txtId.getText()));
        JOptionPane.showMessageDialog(this, mensaje);
        this.cargarDatosTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.vizualizarDatos(-1);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTestigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTestigoFocusLost
        Persona p = this.registroControlador.buscarPersona(txtTestigo.getText());
        lblTestigo.setText(p.getNombre() + " " + p.getApellido());
    }//GEN-LAST:event_txtTestigoFocusLost

    private void txtEsposaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEsposaFocusLost
        Persona p = this.registroControlador.buscarPersona(txtEsposa.getText());
        lblEsposa.setText(p.getNombre() + " " + p.getApellido());
    }//GEN-LAST:event_txtEsposaFocusLost

    private void txtAutoridadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutoridadFocusLost
        Persona p = this.registroControlador.buscarPersona(txtAutoridad.getText());
        lblAutoridad.setText(p.getNombre() + " " + p.getApellido());
    }//GEN-LAST:event_txtAutoridadFocusLost

    private void txtAutoridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutoridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutoridadActionPerformed

    private void txtTestigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTestigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestigoActionPerformed

    private void txtTestigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTestigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestigo2ActionPerformed
    public ResourceBundle getRecurso() {
        return recurso;
    }

    public void setRecurso(ResourceBundle recurso) {
        this.recurso = recurso;
    }
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrimonioVista().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutoridad;
    private javax.swing.JLabel lblAutoridadPresentacion;
    private javax.swing.JLabel lblEsposa;
    private javax.swing.JLabel lblEsposaPresentacion;
    private javax.swing.JLabel lblEsposo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblTestigo;
    private javax.swing.JLabel lblTestigosPresentacion;
    private javax.swing.JTable tblMatrimonio;
    private javax.swing.JTextField txtAutoridad;
    private javax.swing.JTextField txtConyuge2;
    private javax.swing.JTextField txtEsposa;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtTestigo;
    private javax.swing.JTextField txtTestigo2;
    // End of variables declaration//GEN-END:variables
}
