/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.Vista;

import ec.edu.ups.Controlador.Controlador;
import ec.edu.ups.Modelo.Persona;
import java.io.IOException;


/**
 *
 * 
 */
public class VtnPrincipal extends javax.swing.JFrame {

   private Controlador<Persona> controladorPersona;
    
   

    /**
     * Creates new form VtnAdministrador
     */
    public VtnPrincipal() {
        
        controladorPersona = new Controlador<Persona>() {
            @Override
            public boolean validar(Persona obj) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        try {
            controladorPersona.leerArchivo();
        } catch (IOException | ClassNotFoundException ex) {
          

        }
        initComponents();
        this.setLocationRelativeTo(null);
      

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        dtkAdministrador = new javax.swing.JDesktopPane();
        infPrincipal = new javax.swing.JInternalFrame();
        mnuAdministradorPrincipal = new javax.swing.JMenuBar();
        mnuBanco = new javax.swing.JMenu();
        mnuMatrimonios = new javax.swing.JMenuItem();
        mnuPersonas = new javax.swing.JMenuItem();
        mnuAutoridades = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        infPrincipal.setVisible(true);

        javax.swing.GroupLayout infPrincipalLayout = new javax.swing.GroupLayout(infPrincipal.getContentPane());
        infPrincipal.getContentPane().setLayout(infPrincipalLayout);
        infPrincipalLayout.setHorizontalGroup(
            infPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        infPrincipalLayout.setVerticalGroup(
            infPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        dtkAdministrador.setLayer(infPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dtkAdministradorLayout = new javax.swing.GroupLayout(dtkAdministrador);
        dtkAdministrador.setLayout(dtkAdministradorLayout);
        dtkAdministradorLayout.setHorizontalGroup(
            dtkAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infPrincipal)
        );
        dtkAdministradorLayout.setVerticalGroup(
            dtkAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infPrincipal)
        );

        mnuAdministradorPrincipal.setBackground(new java.awt.Color(255, 102, 51));
        mnuAdministradorPrincipal.setForeground(new java.awt.Color(255, 102, 0));

        mnuBanco.setText("Registro");

        mnuMatrimonios.setText("Ver Matrimonios ");
        mnuMatrimonios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMatrimoniosActionPerformed(evt);
            }
        });
        mnuBanco.add(mnuMatrimonios);

        mnuPersonas.setText("Ver Personas");
        mnuPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPersonasActionPerformed(evt);
            }
        });
        mnuBanco.add(mnuPersonas);

        mnuAutoridades.setText("Ver Autoridades");
        mnuAutoridades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAutoridadesActionPerformed(evt);
            }
        });
        mnuBanco.add(mnuAutoridades);

        mnuAdministradorPrincipal.add(mnuBanco);

        setJMenuBar(mnuAdministradorPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtkAdministrador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtkAdministrador)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAutoridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAutoridadesActionPerformed
       /*
        vtnHipoteca = new VtnHipoteca(controladorPrincipal, recurso);
        vtnHipoteca.setRecurso(recurso);
        vtnHipoteca.cambiarIdioma();
        infPrincipal.setTitle("Hipotecas");
        infPrincipal.setContentPane(vtnHipoteca);
        infPrincipal.setVisible(true);
        dtkAdministrador.moveToFront(infPrincipal);
        */

    }//GEN-LAST:event_mnuAutoridadesActionPerformed

    private void mnuMatrimoniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMatrimoniosActionPerformed
        /*
        vtnCasa = new VtnCasa(controladorPrincipal, recurso);
        vtnCasa.setRecurso(recurso);
        vtnCasa.cambiarIdioma();
        infPrincipal.setTitle("Casas");
        infPrincipal.setContentPane(vtnCasa);
        infPrincipal.setVisible(true);
        dtkAdministrador.moveToFront(infPrincipal);
        */
    }//GEN-LAST:event_mnuMatrimoniosActionPerformed

    private void mnuPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPersonasActionPerformed
       
        PersonaVista personaVista= new PersonaVista(controladorPersona);
        
        infPrincipal.setTitle("Personas");
        infPrincipal.setContentPane(personaVista);
        infPrincipal.setVisible(true);
        dtkAdministrador.moveToFront(infPrincipal);
        
    }//GEN-LAST:event_mnuPersonasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    

   

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtkAdministrador;
    private javax.swing.JInternalFrame infPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar mnuAdministradorPrincipal;
    private javax.swing.JMenuItem mnuAutoridades;
    private javax.swing.JMenu mnuBanco;
    private javax.swing.JMenuItem mnuMatrimonios;
    private javax.swing.JMenuItem mnuPersonas;
    // End of variables declaration//GEN-END:variables
}
